//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesTareas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorreoAdjuntos
    {
        public int Id { get; set; }
        public int CorreoId { get; set; }
        public string NombreArchivo { get; set; }
        public string Contenido { get; set; }
        public string TextoReconocido { get; set; }
        public string tEstado { get; set; }
    }
}
