//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesTareas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correos
    {
        public int Id { get; set; }
        public string MessageId { get; set; }
        public string Para { get; set; }
        public string CC { get; set; }
        public string Asunto { get; set; }
        public string Cuerpo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaTranscripcion { get; set; }
        public string De { get; set; }
        public string CartaTranscripcion { get; set; }
        public string FormatoWebArl { get; set; }
        public string FechaCovid { get; set; }
        public string NombresYApellidos { get; set; }
        public string NumeroDocumento { get; set; }
        public string NumeroTelefonico { get; set; }
        public string Edad { get; set; }
        public string Ciudad { get; set; }
        public string CodigoEL { get; set; }
        public string CodigoCTO { get; set; }
        public string EPS { get; set; }
        public string Empresa { get; set; }
        public string CorreoEmpresa { get; set; }
        public string AFP { get; set; }
        public string Cargo { get; set; }
        public string CorreoPaciente { get; set; }
        public string TipoPrueba { get; set; }
        public string CargoNombreArchivo { get; set; }
        public string CargoGuid { get; set; }
        public string EdadNombreArchivo { get; set; }
        public string EdadGuid { get; set; }
        public string EmpresaNombreArchivo { get; set; }
        public string EmpresaGuid { get; set; }
        public string CorreoEmpresaNombreArchivo { get; set; }
        public string CorreoEmpresaGuid { get; set; }
        public string EPSNombreArchivo { get; set; }
        public string EPSGuid { get; set; }
        public string NumeroDocumentoNombreArchivo { get; set; }
        public string NumeroDocumentoGuid { get; set; }
        public string NombresYApellidosNombreArchivo { get; set; }
        public string NumeroTelefonicoNombreArchivo { get; set; }
        public string NombresYApellidosGuid { get; set; }
        public string NumeroTelefonicoGuid { get; set; }
        public string AFPNombreArchivo { get; set; }
        public string AFPGuid { get; set; }
        public string FechaCovidNombreArchivo { get; set; }
        public string FechaCovidGuid { get; set; }
        public string FechaHistoriaClinica { get; set; }
    }
}
