//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesTareas
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextoReconocidoCartas
    {
        public int Id { get; set; }
        public string NombreArchivo { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Contrato { get; set; }
        public string Empresa { get; set; }
        public string EmpresaCorreo { get; set; }
    }
}
