@startuml
start
skinparam handwritten true
partition Preaprobacion {
    repeat :Elaborar depuracion contable (**Borrador**);
    :Enviar a preaprobadores \n**Por Preaprobar**;
    note left: En este momento ya no se pueden \nmodificar las depuraciones
    note left: Actualizar los estados de los\npreaprobadores a **pendiente**
    :Notificar a preaprobadores;
    note left: Se envia adjunto el pdf de la\n depuracion contable
    backward:Cambiar a **Rechazada**\nNotificar preaprobadores;
    note right: Se notifica a los preaprobadores el rechazo
    repeat while (Aprobacion unanime por \npreaprobadores) is (**No**)
    ->**Si**;
    :Cambiar a **Preaprobada**;
}
partition Aprobacion {
    :Enviar correo para aprobacion al\n aprobador de la entidad;
    note left: Se envia adjunto el pdf de la\n depuracion contable
    if (Aprobacion por aprobador) then(**Si**)
        :Cambiar estado a **Aprobada**;
    else(**No**)

        :Cambiar estado a **Rechazada**;
    endif
    stop
}
@enduml