@startuml
start
skinparam handwritten true
:Subir excel de depuracion contable\n(estado a **Preaprobada**);
partition Aprobacion {
    note left: Se notifica al aprobador de famisanar\n depuracion contable?
    if (Aprobacion por aprobador) then(**Si**)
        :Cambiar estado a **Aprobada**;
    else(**No**)

        :Cambiar estado a **Rechazada**;
    endif
    stop
}
@enduml