@startuml
start
if (El archivo es csv?) then (si)
else (no)
  :Devolver error de formato;
  stop
endif
:Constrouir modelo de entrada;
:Persistir peticion de cargue\n en la Db de Cosmos;
:Filtrar medicos obsoletos;
:Filtrar medicos vigentes;
:Filtrar medicos faltantes;
:Consultar medicos faltantes;
:Actualizar medicos faltantes;
:
end
@enduml