//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosTareas.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carta
    {
        public int Id { get; set; }
        public string TextoTranscripcion { get; set; }
        public string FormatoWebArl { get; set; }
    }
}
