//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosTareas.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorreoAdjuntos
    {
        public int Id { get; set; }
        public int CorreoId { get; set; }
        public string NombreArchivo { get; set; }
        public string Contenido { get; set; }
        public string TextoReconocido { get; set; }
        public string tEstado { get; set; }
    }
}
