//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntidadesTareas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kustodyaEntities : DbContext
    {
        public kustodyaEntities()
            : base("name=kustodyaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carta> Carta { get; set; }
        public virtual DbSet<CorreoAdjuntos> CorreoAdjuntos { get; set; }
        public virtual DbSet<Correos> Correos { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<TextoReconocidoCartas> TextoReconocidoCartas { get; set; }
    }
}
